
(() => {
  'use strict';
  const $ = s => document.querySelector(s), SAVE = 'duskborn-save-v1';
  const canvas=$('#world'), ctx=canvas.getContext('2d'); ctx.imageSmoothingEnabled=false;
  const CLASS={warrior:{might:3,finesse:1,wits:1,charm:2},rogue:{might:1,finesse:3,wits:2,charm:1},mage:{might:1,finesse:1,wits:3,charm:2},trickster:{might:1,finesse:2,wits:2,charm:3}};
  const QUIRKS=['counts every exit','laughs when frightened','never turns their back on a grave','keeps one clean glove','speaks softly to dead things'];
  const SECRETS=['owes a blood debt beyond the fen','once heard a voice beneath the crypt','stole a page from the village charter','dreamed of Kaethas before the Rising'];
  const PLACES={
    tavern:{name:'The Ember & Ash',x:3,y:4,box:[1,1,4,3],color:'#754b3f'}, elders_hall:{name:"Elder's Hall",x:10,y:4,box:[8,1,4,3],color:'#66506d'}, chapel:{name:'Chapel of the Veil',x:16,y:4,box:[14,1,4,3],color:'#59687c'},
    graveyard:{name:'The Graveyard',x:0,y:5,color:'#4e665b'}, square:{name:'Village Square',x:10,y:5,color:'#8d765a'}, cryptgate:{name:'The Crypt Gate',x:19,y:5,color:'#51384f'},
    smithy:{name:"Hetta's Forge",x:3,y:6,box:[1,7,4,3],color:'#8a513c'}, market:{name:'Market Row',x:10,y:6,box:[8,7,4,3],color:'#6b6245'}, lantern:{name:'The Velvet Lantern',x:16,y:6,box:[14,7,4,3],color:'#71465f'}, wheatfields:{name:'Wheatfield Road',x:10,y:10,color:'#8c7545'}
  };
  const PEOPLE={wren:{name:'Wren',x:8,y:5,color:'#7fa2a1'},sera:{name:'Sera',x:12,y:5,color:'#ded3b0'},garrick:{name:'Garrick',x:10,y:6,color:'#7f3c45'},maer:{name:'Maer',x:10,y:4,color:'#967a9c'},aldric:{name:'Aldric',x:1,y:5,color:'#93a08c'},kaethas:{name:'Kaethas',x:18,y:5,color:'#a98255'},bram:{name:'Bram',x:4,y:5,color:'#9a6b4f'},hetta:{name:'Hetta',x:4,y:6,color:'#b06043'},odo:{name:'Odo',x:11,y:6,color:'#9a8b58'},vessa:{name:'Vessa',x:16,y:6,color:'#a45f81'}};
  const PERSON_PLACE={wren:'square',sera:'square',garrick:'square',maer:'elders_hall',aldric:'graveyard',kaethas:'cryptgate',bram:'tavern',hetta:'smithy',odo:'market',vessa:'lantern'};
  const ACTIONS={
    wren:{stat:'charm',dc:8,ok:'Wren finally tells you what she saw: Maer slipped from the crypt with a burning ledger page while the first grave opened. Her fear loosens into purpose. She will leave if you ask.',bad:'Wren folds around her secret. “Not here. Not with everyone looking at you like that.” She retreats toward the fields.',apply:(ok)=>{if(ok){flag('wren_leaving');know('wren','trusted the player with what she saw');mood('wren',12)}}},
    armor:{stat:'charm',dc:12,ok:'Aldric studies you for a long time, then opens the grave-shed. His old crusader mail smells of lamp oil and smoke. “Armor remembers what was done inside it,” he says. “Give it a better memory.”',bad:'Aldric keeps one hand on the grave-shed key. “Not yet. I know the look of borrowed courage.” The old armor stays behind its oak door.',apply:(ok)=>{if(ok){flag('aldric_armor');addItem('Aldric’s mail');mood('aldric',15)}}},
    spear:{stat:'might',dc:12,ok:'You hold the half-made Dawnbrand steady while Hetta drives the final rivet. Silver screams against iron. She gives you the spearhead without smiling. “Make the dead regret standing up.”',bad:'The hot haft twists from your grip and bites the dirt. Hetta catches it before it cracks. “Strength is not noise,” she says, taking it back.',apply:(ok)=>{if(ok){flag('hetta_spear');addItem('Dawnbrand spear');mood('hetta',15)}}},
    salt:{stat:'wits',dc:12,ok:'You show Sera where the old ward-circle broke. Her doubt becomes motion. She presses two sacks of grave-salt into your arms and begins marking every threshold in the square.',bad:'Your ward marks cross themselves and gutter. Sera sweeps the salt back into its jar. “Guessing with holy things kills whoever trusts you.”',apply:(ok)=>{if(ok){flag('sera_salt');addItem('Grave-salt');mood('sera',15)}}},
    militia:{stat:'charm',dc:12,ok:'Bram plants his cudgel on the bar. One stool scrapes back, then another. Six frightened drinkers become a ragged militia because you gave their fear a direction.',bad:'Your speech dies between the tables. Bram keeps polishing the same cup. “Fine words,” he says. “The dead eat those first.”',apply:(ok)=>{if(ok){flag('bram_militia');mood('bram',15)}}},
    tablet:{stat:'wits',dc:16,ok:'Behind the village charter you find a founder’s tablet, its murder scratched in Kaethas’s own hand. Maer’s bloodline stole Duskmere by poison. The dead have not come for conquest. They have come to collect.',bad:'The archive gives you dust, mouse bones, and a page recently cut from the ledger. Maer watches from the doorway without blinking.',apply:(ok)=>{if(ok){flag('knows_founder_truth');flag('has_tablet');addItem('Founder’s tablet');mood('maer',-18)}}},
    vessa:{stat:'charm',dc:12,ok:'Vessa takes your coin, then returns it. “Maer visits the crypt gate after midnight. Ask why the dead call her oathbreaker.” In the Lantern, a free truth is always the most expensive kind.',bad:'Vessa smiles as if you offered her a child’s marble. “Secrets are not rescued, darling. They are purchased.” The velvet curtain closes.',apply:(ok)=>{if(ok){flag('knows_founder_truth');mood('vessa',8)}}},
    wagon:{stat:'finesse',dc:16,ok:'Odo never hears you lift the wagon key. The fast mule is harnessed behind Market Row. One hard choice now has a road attached to it.',bad:'The key ring chimes once. Odo’s knife appears under your ribs. “Try that after I’m dead,” he whispers, loud enough for the market to hear.',apply:(ok)=>{if(ok){flag('odo_wagon');addItem('Wagon key');change('deceit',4);change('hunger',2)}}},
    poison:{stat:'finesse',dc:16,ok:'The powder vanishes into the well. A shutter closes above the square. You do not look up. By morning, Duskmere will be too sick to resist anything.',bad:'The packet tears against the windlass. Bitter powder stripes your sleeve as Sera steps from the chapel. The bell begins ringing before you can run.',apply:(ok)=>{change('brutality',7);change('shadow',5);if(ok)flag('well_poisoned');else{mood('sera',-35);state.clocks.wrath=Math.min(6,state.clocks.wrath+1)}}},
    seal:{stat:'wits',dc:16,ok:'You turn the lowest ward-stone backward. The crypt sighs like a lung. Kaethas tilts his crowned skull toward you—not grateful, exactly, but interested.',bad:'The seal flares under your hand and brands an open eye into your palm. Every corpse beyond the gate turns to look. Kaethas laughs once.',apply:(ok)=>{change('shadow',7);change('hunger',4);if(ok)flag('seal_sabotaged');else hurt(2)}}
  };
  let state=null,busy=false,selected='warrior',near='square',lastAction='';
  function normalizeLocation(id){if(id==='hall')return'elders_hall';return (id&&PLACES[id])?id:'square'}
  function fresh(name,kind){return {version:1,name,kind,stats:{...CLASS[kind]},quirk:pick(QUIRKS),secret:pick(SECRETS),x:10,y:5,location:'square',hp:10,hpMax:10,gold:8,inventory:[],personality:{presence:50,brutality:45,deceit:45,hunger:45,shadow:8},flags:{},clocks:{dusk:0,wrath:0},turn:0,events:[],npcs:Object.fromEntries(Object.keys(PEOPLE).map(id=>[id,{disposition:id==='wren'?50:0,status:'alive',knows:[]} ])),opening:false,ending:null};}
  function hydrate(raw){const kind=(raw&&CLASS[raw.kind])?raw.kind:'warrior',base=fresh((raw&&typeof raw.name==='string')?raw.name:'Maker',kind),m={...base,...raw};m.stats={...base.stats,...(raw&&raw.stats)};m.personality={...base.personality,...(raw&&raw.personality)};m.clocks={...base.clocks,...(raw&&raw.clocks)};m.flags={...(raw&&raw.flags||{})};m.inventory=Array.isArray(raw&&raw.inventory)?raw.inventory:[];m.events=Array.isArray(raw&&raw.events)?raw.events:[];m.npcs={...base.npcs,...(raw&&raw.npcs)};for(const id of Object.keys(base.npcs)){m.npcs[id]={...base.npcs[id],...(m.npcs[id]||{})};if(!Array.isArray(m.npcs[id].knows))m.npcs[id].knows=[]}if(m.location==='hall')m.location='elders_hall';m.location=normalizeLocation(m.location);m.hpMax=clamp(+m.hpMax||10,1,10);m.hp=clamp(+m.hp||0,0,m.hpMax);m.gold=Math.max(0,+m.gold||0);m.clocks.dusk=clamp(+m.clocks.dusk||0,0,3);m.clocks.wrath=clamp(+m.clocks.wrath||0,0,6);m.x=clamp(+m.x||10,0,19);m.y=clamp(+m.y||5,0,10);if(m.flags.spared_garrick||m.flags.robbed_garrick||m.flags.killed_garrick)m.opening=true;return m}
  function pick(a){return a[Math.floor(Math.random()*a.length)]} function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
  function flag(k){state.flags[k]=true} function change(k,n){state.personality[k]=clamp(state.personality[k]+clamp(n,-10,10),0,100)} function mood(id,n){if(state.npcs[id])state.npcs[id].disposition=clamp(state.npcs[id].disposition+n,-100,100)} function know(id,s){if(state.npcs[id]&&!state.npcs[id].knows.includes(s))state.npcs[id].knows.push(s)} function addItem(s){if(!state.inventory.includes(s))state.inventory.push(s)} function hurt(n){state.hp=clamp(state.hp-n,0,state.hpMax)}
  function toast(s){const e=$('#toast');e.textContent=s;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2800)}
  function save(silent=true){if(!state)return;localStorage.setItem(SAVE,JSON.stringify(state));if(!silent)toast('Life written locally')}
  function overlayOpen(){return ['cover','cinema','die','ending'].some(id=>!$('#'+id).classList.contains('hidden'))}
  function syncControls(){const living=!!state&&!state.ending,canAct=living&&!busy,canWalk=canAct&&state.opening;$('#actionInput').disabled=!canAct;$('#act').disabled=!canAct;$('#interactBtn').disabled=!canWalk}
  function enterGame(){$('#cover').classList.add('hidden');$('#game').classList.remove('creating');syncControls()}
  function begin(){const name=$('#name').value.trim()||'Maker';state=fresh(name,selected);near=normalizeLocation(state.location);enterGame();opening();update();save()}
  function resume(){try{const raw=JSON.parse(localStorage.getItem(SAVE));if(!raw)throw Error('empty');state=hydrate(raw);near=normalizeLocation(state.location);enterGame();if(state.ending){$('#endingTitle').textContent=state.ending.title;$('#endingText').textContent=state.ending.text;$('#ending').classList.remove('hidden')}else if(!state.opening){opening()}else{show('Returned to Duskmere','The village is exactly as you left it. That is not the same as unchanged.',[['Walk the village','back','']])}update()}catch{localStorage.removeItem(SAVE);toast('Saved life could not be read')}}
  function opening(){show('Village Square','The first sunset since Kaethas’s ultimatum bleeds over Duskmere. Garrick—the looter who stripped your mother’s body during the Rising—crawls beside the well with her silver signet clenched in his fist. Wren sees you. Sera sees you. Beyond them, the dead at the crypt gate turn their skulls toward the square.',[
    ['Bind his wound','spare','mercy'],['Take back the ring','rob',''],['Finish him','kill','danger']]);}
  function show(title,text,choices=[]){$('#sceneTitle').textContent=title;$('#narration').textContent=text;const box=$('#choices');box.textContent='';choices.forEach(([label,code,cls])=>{const b=document