.createElement('button');b.textContent=label;b.className=cls||'';b.onclick=()=>choose(code);box.appendChild(b)});}
  async function choose(code){if(busy)return;if(['spare','rob','kill'].includes(code))return firstChoice(code);if(code==='back'){show(PLACES[near].name,'The village waits. Move with WASD or arrows. Stand beside a person or door, then press E / Enter / Interact. Or press T and type what you do.');return}if(code==='rest'){const text='The velvet curtain closes on consenting adults. Later, you step back into the cold with your wounds washed, your purse lighter, and one useful rumor: Maer walks to the crypt after midnight.';state.gold=Math.max(0,state.gold-3);state.hp=Math.min(state.hpMax,state.hp+2);change('hunger',2);record(text);show('The Velvet Lantern',text,[['Back to the road','back','']]);cinematic('Behind the velvet curtain','The door closes. The story resumes afterward, with candle smoke in your clothes and a secret in your pocket.');update();return}if(code==='join')return end('join_warlord','THE BONE HEIR','You take Kaethas’s bronze hand. By midnight the village kneels; by dawn, those who refused no longer have knees. The dead name you heir, and every grave in the Barrowfen opens like an eye.');if(code==='flee')return end('flee','ASH AT YOUR BACK','The wagon takes the wheatfield road while the third bell rings. Duskmere becomes a red bruise on the horizon. You live. Some nights, survival and cowardice wear the same face.');if(code==='truth')return end('judge_elder',"THE FOUNDER'S DUE",'You give Maer the tablet and Kaethas her name. The dead take one life with terrible ceremony, then return to their graves. Duskmere survives beneath a truth nobody can bury again.');if(code==='stand')return finalStand();if(code==='betray')return end('betray_village','THE QUIET KNIFE','When the dead press the gate, the ward fails from within. Duskmere never sees the hand that killed it. Kaethas does. He keeps a place at his right side for useful monsters.');if(ACTIONS[code])return actionCheck(code);}
  async function firstChoice(kind){const check={spare:['wits',8],rob:['finesse',12],kill:['might',8]}[kind];const r=await roll(check[0],check[1],'none');let text='';if(kind==='spare'){flag('spared_garrick');change('brutality',-8);change('presence',3);mood('wren',12);mood('sera',10);state.npcs.garrick.status='wounded';addItem('Mother’s signet');text=r.ok?'Your hands stop the blood. Garrick gives back the signet and a name: he saw Maer at the crypt before the Rising. Wren exhales. Sera kneels beside you without being asked.':'The knot slips and Garrick nearly bleeds out, but you keep pressure until Sera takes over. Mercy looks clumsy on you. It is mercy anyway.'}
    if(kind==='rob'){flag('robbed_garrick');change('deceit',4);change('hunger',4);mood('wren',-8);know('wren','saw the player rob Garrick while he bled');addItem('Mother’s signet');state.gold+=r.ok?5:0;text=r.ok?'Your fingers lift the signet and Garrick’s last five coins before Sera turns. Wren saw. Her face closes like a door.':'Garrick catches your wrist and screams thief. You wrench the ring free, but now the whole square knows what you reached for first.'}
    if(kind==='kill'){flag('killed_garrick');change('brutality',10);change('shadow',3);mood('wren',-25);mood('sera',-35);know('sera','watched the player kill a wounded man');state.npcs.garrick.status='dead';addItem('Mother’s signet');if(!r.ok)hurt(2);text=r.ok?'One clean blow drives Garrick’s face into the well-stone. The signet comes loose with two teeth. Sera whispers your name as if testing whether it still belongs to you.':'Garrick’s hidden knife opens your side before you break his neck against the well. You get the signet. You also get the silence after.'}
    state.opening=true;record(text);show('The choice is witnessed',text,[['Walk the village','back','']]);cinematic(kind==='kill'?'The well-stone remembers':'The first mark',text);update();}
  async function actionCheck(code){const a=ACTIONS[code],adv=advantageFor(code);show(PLACES[normalizeLocation(state.location||near)].name,'The next breath belongs to chance.');const r=await roll(a.stat,a.dc,adv);a.apply(r.ok,r);record(r.ok?a.ok:a.bad);show(PLACES[near].name,r.ok?a.ok:a.bad,[['Back to the road','back','']]);update();}
  function advantageFor(code){if(code==='salt'&&state.flags.spared_garrick)return'advantage';if(code==='militia'&&state.personality.presence>=65)return'advantage';if((code==='poison'||code==='wagon')&&state.personality.deceit>=65)return'advantage';return'none'}
  async function roll(stat,dc,adv='none'){setBusy(true);const face=$('#dieFace'),text=$('#dieText'),cap=$('#dieCap'),advEl=$('#dieAdv'),hint=$('#dieHint'),box=$('#die');const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;
    face.className='die-face';cap.textContent=`${stat.toUpperCase()} · DC ${dc}`;advEl.className='die-adv hidden';if(adv==='advantage'){advEl.textContent='Advantage · roll 2, keep high';advEl.className='die-adv up'}else if(adv==='disadvantage'){advEl.textContent='Disadvantage · roll 2, keep low';advEl.className='die-adv down'}text.textContent='The die is still moving.';if(hint)hint.textContent='';box.classList.remove('hidden');
    let a=1+Math.floor(Math.random()*20),b=1+Math.floor(Math.random()*20),natural=adv==='advantage'?Math.max(a,b):adv==='disadvantage'?Math.min(a,b):a;
    if(reduce){face.textContent=natural}else{face.classList.add('rolling');const flick=setInterval(()=>{face.textContent=1+Math.floor(Math.random()*20)},55);await wait(700);clearInterval(flick);face.classList.remove('rolling');face.textContent=natural}
    const mod=state.stats[stat]*2,total=natural+mod,ok=natural===20||(natural!==1&&total>=dc);
    const label=natural===20?'LEGENDARY':natural===1?'CATASTROPHE':ok?(total>=dc+5?'STRONG SUCCESS':'SUCCESS'):(total<=dc-5?'HARD FAILURE':'FAILURE');
    const outcome=natural===20?'crit_success':natural===1?'crit_failure':ok?(total>=dc+5?'strong_success':'success'):(total<=dc-5?'hard_failure':'failure');
    face.classList.add(natural===20?'crit':natural===1?'fumble':ok?'win':'lose');text.textContent=`${natural} + ${mod} = ${total}  vs  DC ${dc}  ·  ${label}`;if(hint)hint.textContent='Click or press Enter to continue';
    await waitForDieAck(box);box.classList.add('hidden');if(hint)hint.textContent='';setBusy(false);return{stat,roll:natural,modifier:mod,total,dc,outcome,ok}}
  function waitForDieAck(box){return new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;clearTimeout(tid);box.removeEventListener('click',finish);removeEventListener('keydown',onKey);resolve()};const onKey=e=>{if(e.key==='Enter'||e.key===' '||e.key==='Escape'){e.preventDefault();finish()}};box.addEventListener('click',finish);addEventListener('keydown',onKey);const tid=setTimeout(finish,8000)})}
  function personVisible(id){const n=state?.npcs?.[id];if(!n)return false;if(['dead','fled'].includes(n.status)&&id!=='garrick')return false;if(id==='garrick'&&state.opening&&n.status!=='alive'&&n.status!=='wounded')return false;return true}
  function nearestTarget(){let best={id:'square',kind:'place',place:'square',dist:99,label:PLACES.square.name};for(const [id,p] of Object.entries(PLACES)){const d=Math.abs(state.x-p.x)+Math.abs(state.y-p.y);if(d<best.dist)best={id,kind:'place',place:id,dist:d,label:p.name}}for(const [id,p] of Object.entries(PEOPLE)){if(!personVisible(id))continue;const d=Math.abs(state.x-p.x)+Math.abs(state.y-p.y);if(d<best.dist)best={id,kind:'person',place:PERSON_PLACE[id]||'square',dist:d,label:p.name}}return best}
  function refreshPrompt(){const el=$('#mapPrompt');if(!el||!state||!state.opening||state.ending||busy||overlayOpen()){if(el)el.classList.add('hidden');return}const t=nearestTarget();if(t.dist<=1){el.textContent=`E / Interact: ${t.label}`;el.classList.remove('hidden')}else el.classList.add('hidden')}
  function interact(){if(!state||busy||!state.opening||state.ending||overlayOpen())return;const t=nearestTarget();if(t.dist>1){toast(`Move closer to ${t.label}`);return}near=t.place;state.location=near;openPlace(near);save();refreshPrompt()}
  function openPlace(id){const f=state.flags, p=PLACES[id];let text='',choices=[];
    if(id==='square'){text=state.flags.killed_garrick?'The well has been scrubbed, but people step around the dark seam between its stones. Wren will not meet your eyes.':state.flags.robbed_garrick?'Wren keeps her hands in her pockets. Garrick’s blood is still dark in the well mortar, and nobody asks you how the ring came back.':state.flags.spared_garrick?'Garrick is gone from the stones. Sera nods once when she sees you. Wren stays close, as if closeness were a decision.':'People cluster beneath the dusk bell. Wren keeps watching Maer, then the crypt.';choices=[['Ask Wren what she saw','wren',''],['Poison the village well','poison','danger']]}
    if(id==='graveyard'){text='Aldric stands among fresh graves in his old crusader coat. The locked grave-shed behind him smells of oil and iron.';choices=[['Ask for his crusader armor','armor','mercy']]}
    if(id==='smithy'){text='Hetta hammers chapel silver around a black iron core. The half-made Dawnbrand throws pale sparks.';choices=[['Prove you can wield it','spear','']]}
    if(id==='chapel'){text='Sera has drawn one failing ward in grave-salt. Her hands shake only when nobody speaks.';choices=[['Repair the ward and ask for salt','salt','mercy']]}
    if(id==='tavern'){text='The Ember & Ash is full of people pretending not to listen. Bram’s cudgel rests beneath the bar.';choices=[['Turn the drinkers into a militia','militia','']]}
    if(id==='elders_hall'){text='Maer guards the charter cabinet more closely than the village gate. One ledger page has been cut away.';choices=[['Search for the founder’s record','tablet','']]}
    if(id==='lantern'){text='Vessa’s Lantern glows through the curfew. Every curtain hides a bargain; every adult inside knows when to leave one closed.';choices=[['Ask what Maer hides','vessa',''],['Spend the night (fade to black)','rest','']]}
    if(id==='market'){text='Odo has a fast mule harnessed behind shuttered stalls. The wagon key knocks softly against his belt.';choices=[['Steal the wagon key','wagon',''],...(f.odo_wagon?[["Take the road out",'flee','danger']]:[])]}
    if(id==='cryptgate'){text='Kaethas waits beyond the ward-stones in ancient bronze. The silent horde parts for you. “Heir,” he says. “Have you decided what this village is worth?”';choices=[['Join the risen warlord','join','danger'],['Turn a ward-stone inward','seal','danger'],['Stand against him now','stand',''],...(f.knows_founder_truth?[["Give him Maer and the truth",'truth','']]:[])]}
    if(id==='wheatfields'){text='The road is open for one more dusk. Behind you, Duskmere’s bell begins another count.';choices=[[f.odo_wagon?'Leave by wagon':'Run before dark','flee','danger']]}
    show(p.name,text,choices);}
  async function finalStand(){const gear=['aldric_armor','hetta_spear','sera_salt','bram_militia'].filter(x=>st